apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "counterapi.fullname" . }}
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "counterapi.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "counterapi.name" . }}
    spec:
      containers:
        - name: counterapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

