apiVersion: v1
kind: Service
metadata:
  name: {{ include "counterapi.fullname" . }}
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "counterapi.name" . }}

